### ISSUE TITLE
Clarify expected type in fabric.py

### ISSUE THREAD

**Issue by Onager** [libyal/dtfabric#14]
https://github.com/libyal/dtfabric/blob/master/dtfabric/runtime/fabric.py#L18 specifies that the expected type for yaml_definition is str, but this argument is then passed to a BytesIO object.

Please clarify whether this method is intended to take a string or bytes argument.

**Comment by joachimmetz** [comment]
Should be bytes, but I'll fix the docstring.

**Comment by joachimmetz** [comment]
Changes to docstring in https://github.com/libyal/dtfabric/commit/525bc3929426756d3d7c2c40f3b5262b2f38745a
